
# this identifies fields to skip in the config set command list
~/enabled/: false

# enable the plugin
enabled: true

frequency-representation:
  dyes:
    WHITE: "Whi"
    LIGHT_GRAY: "LGr"
    GRAY: "Gra"
    BLACK: "Bla"
    BROWN: "Bro"
    RED: "Red"
    ORANGE: "Ora"
    YELLOW: "Yel"
    LIME: "Lim"
    GREEN: "Gre"
    CYAN: "Cya"
    LIGHT_BLUE: "LBl"
    BLUE: "Blu"
    PURPLE: "Pur"
    MAGENTA: "Mag"
    PINK: "Pin"
  separating-string: "-"

# Field Radio
fieldradio:

  #hide these in set command
  ~/base-material/: false

  audio-filter:
    enabled: true
    LP-alpha: 0.8  # Lower = more muffled
    HP-alpha: 0.85 # Higher = less bass
    noise-floor: 75  # Constant hiss volume
    crackle-chance: 3000 # 1 in 3000 chance per sample

  # this is so that the radio doesn't cut out at the end
  # 200000000 is default at what I believe is .2s
  # this is milliseconds and is NOT based off ticks
  grace-period: 200000000

  # base material the field radio uses, set to use music discs by default
  base-material: MUSIC_DISC_13

  recipe:

    # Crafting the radio
    basic:
      enabled: true

      # # Use 0-9 used for frequencies,
      # Recommended to use 2 frequencies for this
      shape:
        - "C01"
        - "IAI"
        - "IRI"
      ingredients:
        C: "COPPER_INGOT"
        I: "IRON_INGOT"
        R: "REDSTONE"
        A: "AMETHYST_SHARD"

    # Resting the frequency of the radio
    retune:
      enabled: true

      # Use RADIO for radio and DYE for frequencies
      ingredients:
        - "RADIO"
        - "DYE"
        - "DYE"


speaker:

  ~/block/entity/: false

  # weather the speaker uses a block or an entity
  # this is specifically so that you can have the option to override a head
  # or just use an entity and not override any blocks
  use-entity: true

  # cache size for number of stored channels for people speaking on a frequency
  cache-size: 8

  sound-range: 32

  audio-filter:
    enabled: true
    LP-alpha: 0.6  # Lower = more muffled
    HP-alpha: 0.9 # Higher = less bass
    noise-floor: 40  # Constant hiss volume
    crackle-chance: 3000 # 1 in 3000 chance per sample


  recipe:
    basic:
      enabled: true

      # Use 0-9 used for frequencies
      # Recommended to have only one frequency for this
      shape:
        - "0A0"
        - "IRI"
        - "CJC"
      ingredients:
        C: "COPPER_INGOT"
        I: "IRON_INGOT"
        R: "REDSTONE"
        A: "AMETHYST_SHARD"
        J: "JUKEBOX"

    # Resting the frequency of the speaker
    retune:
      enabled: true

      # Use SPEAKER for radio and DYE for frequencies
      ingredients:
        - "SPEAKER"
        - "DYE"

  #used if use-entity is set to false
  block:
    # if changing the head type you MUST update which texture is overridden in the resource pack as well
    # to override that head, Don't forget about that part
    # shouldn't be changing this one in config during server runtime
    head-type: "PIGLIN_HEAD"

    # wall heads use a different material so while this could in theory be a different head type
    # I recommend keeping this as just the wall variant of the head bing used for head-type
    # shouldn't be changing this one in config during server runtime
    wall-head-type: "PIGLIN_WALL_HEAD"

  # used if use-entity is set to true
  # shouldn't be changing this one in config during server runtime
  entity:
    # base material the speaker uses, needs to be one which can be placed
    base-material: DARK_OAK_BUTTON

    # .5 0 .5 sets it at the regular block placement
    display-offset:
      x: 0.5
      y: 0.5
      z: 0.5

    interaction-width: .6
    interaction-height: .6

microphone:
  #hide these in set command
  ~/entity/: false

  # range in which it can be used
  use-range: 3

  # applied when talking through microphone
  audio-filter:
    enabled: false # if this is too intensive on the server you can disable it with this
    LP-alpha: 0.8  # Lower = more muffled
    HP-alpha: 0.8 # Higher = less bass
    noise-floor: 0  # Constant hiss volume
    crackle-chance: 999 # 1 in 3000 chance per sample

  recipe:
    basic:
      enabled: true

      # Use 0-9 used for frequencies
      # Recommended to have only one frequency for this
      shape:
        - " 0 "
        - "IAI"
        - " D "
      ingredients:
        I: "IRON_INGOT"
        A: "AMETHYST_SHARD"
        D: "DIAMOND"

    # Resting the frequency of the speaker
    retune:
      enabled: true

      # Use SPEAKER for radio and DYE for frequencies
      ingredients:
        - "MICROPHONE"
        - "DYE"

  # used if use-entity is set to true
  # shouldn't be changing this one in config during server runtime
  entity:
    # base material the speaker uses, needs to be one which can be placed
    base-material: DARK_OAK_BUTTON

    # .5 0 .5 sets it at the regular block placement
    display-offset:
      x: 0.5
      y: 0.5
      z: 0.5

    interaction-width: .6
    interaction-height: .6
