
# this identifies fields to skip in the config set command list
~/enabled/: false

# enable the plugin
enabled: true

frequency-representation:
  dyes:
    WHITE: "Whi"
    LIGHT_GRAY: "LGr"
    GRAY: "Gra"
    BLACK: "Bla"
    BROWN: "Bro"
    RED: "Red"
    ORANGE: "Ora"
    YELLOW: "Yel"
    LIME: "Lim"
    GREEN: "Gre"
    CYAN: "Cya"
    LIGHT_BLUE: "LBl"
    BLUE: "Blu"
    PURPLE: "Pur"
    MAGENTA: "Mag"
    PINK: "Pin"
  separating-string: "-"

# Field Radio
fieldradio:
  audio-filter:
    enabled: true
    volume: 1.6  # Gain
    LP-alpha: 0.8  # Lower = more muffled
    HP-alpha: 0.85 # Higher = less bass
    noise-floor: 75  # Constant hiss volume
    crackle-chance: 3000 # 1 in 3000 chance per sample

  # this is so that the radio doesn't cut out at the end
  # 200000000 is default at what I believe is .2s
  # this is milliseconds and is NOT based off ticks
  grace-period: 200000000

  recipe:

    # Crafting the radio
    basic:
      enabled: true

      # Use 0 for main frequency and numbers 1 - 9 for subfrequencies,
      # Recommended to have a main frequency and one subfrequency
      shape:
        - "C01"
        - "IAI"
        - "IRI"
      ingredients:
        C: "COPPER_INGOT"
        I: "IRON_INGOT"
        R: "REDSTONE"
        A: "AMETHYST_SHARD"

    # Crafting the Broadcast radio
    broadcast:
      enabled: true

      # Use 0 for main frequency and numbers 1 - 9 for subfrequencies,
      # Recommended to have a main frequency and one subfrequency
      shape:
        - "0A0"
        - "IDI"
        - "0C0"
      ingredients:
        C: "COPPER_INGOT"
        I: "IRON_INGOT"
        R: "REDSTONE"
        A: "AMETHYST_SHARD"

    # Resting the frequency of the radio
    retune:
      enabled: true

      # Use RADIO for radio and DYE for frequencies
      ingredients:
        - "RADIO"
        - "DYE"
        - "DYE"


speaker:
  audio-filter:
    enabled: true
    volume: 1.6  # Gain
    LP-alpha: 0.6  # Lower = more muffled
    HP-alpha: 0.9 # Higher = less bass
    noise-floor: 40  # Constant hiss volume
    crackle-chance: 3000 # 1 in 3000 chance per sample

  ~/block/entity/: false

  # currentley no functionality for using entities instead
  use-entity: false

  sound-range: 32

  recipe:
    basic:
      enabled: true

      # Use 0 for main frequency and numbers 1 - 9 for subfrequencies,
      # Recommended to have only a main frequency
      shape:
        - "0A0"
        - "IRI"
        - "CJC"
      ingredients:
        C: "COPPER_INGOT"
        I: "IRON_INGOT"
        R: "REDSTONE"
        A: "AMETHYST_SHARD"
        J: "JUKEBOX"

    # Resting the frequency of the speaker
    retune:
      enabled: true

      # Use SPEAKER for radio and DYE for frequencies
      ingredients:
        - "SPEAKER"
        - "DYE"

  #used if use-entity is set to false
  block:
    # if changing the head type you MUST update which texture is overridden in the resource pack as well
    # to override that head, Don't forget about that part
    # shouldn't be changing this one in config during server runtime
    head-type: "PIGLIN_HEAD"

    # wall heads use a different material so while this could in theory be a different head type
    # I recommend keeping this as just the wall variant of the head bing used for head-type
    # shouldn't be changing this one in config during server runtime
    wall-head-type: "PIGLIN_WALL_HEAD"

    # used if use-entity is set to true
    # shouldn't be changing this one in config during server runtime
  entity: ""
